name = "balaji-ludo-king"
main = "worker.js"
compatibility_date = "2026-09-12"

[assets]
directory = "./Public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "LUDO_ROOM"
class_name = "LudoRoom"

[[migrations]]
tag = "v4"
