name = "balaji-ludo-king"
main = "worker.js"
compatibility_date = "2026-09-12"

[assets]
directory = "./public"

[[durable_objects.bindings]]
name = "LUDO_ROOM"
class_name = "LudoRoom"

[[durable_objects.bindings]]
name = "CUSTOMER_STORE"
class_name = "CustomerStore"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LudoRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["CustomerStore"]

[[migrations]]
tag = "v3"
new_sqlite_classes = []
